#!/usr/bin/bash
echo "Введите путь до компилируемого файла: "
read way
cowsay -f stimpy "Начинаю хуярить через..."
sleep 2
echo "3"
sleep 2
echo "2"
sleep 2
echo "1"
sleep 2
echo "Полетели. Для запуска исполняемого файла нажмите ctrl+z"
sleep 2
while :
    do
	g++ $way -lm -o ${way%%.cpp}
	#i686-w64-mingw32-g++ -o ${1%%.cpp}32.exe $1
	#x86_64-w64-mingw32-gcc -o ${1%%.cpp}64.exe $1
	#i686-w64-mingw32-g++ -static-libgcc -static-libstdc++ $1
	trap "./${way%%.cpp}" SIGTSTP
    done
